apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dockergen
  name: dockergen
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dockergen
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: dockergen
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      containers:
      - name: dockergen
        image: chaos.azurecr.io/dockergen:v0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "50Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      imagePullSecrets:
        - name: azure-cr
---

apiVersion: v1
kind: Service
metadata:
  namespace: dockergen
  name: dockergen
  labels:
    name: dockergen
spec:
  type: ClusterIP
  ports:
  - port: 443
  selector:
    app: dockergen
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: dockergen
  name: dockergen
  annotations:
    "kubernetes.io/ingress.class": "kempLB"
    "kemp.ax/vspip": "192.168.6.200"
    "kemp.ax/vsport": "443"
    "kemp.ax/vsprot": "tcp"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - dockergen.frodehus.dev
  rules:
  - host: dockergen.frodehus.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dockergen
            port:
              number: 443