namespace DockerLib.CodeAnalysis.Syntax;
public enum SyntaxKind
{
    WhitespaceToken,
    BadToken,
    EndOfFileToken,

    EqualToken,
    OpenParenthesisToken,
    CloseParenthesisToken,

    //keywords
    FromKeyword,
    RunKeyword,
    CopyKeyword,
    AddKeyword,
    EntrypointKeyword,
    CommandKeyword,
    EnvironmentVariableKeyword,
    BuildArgumentKeyword,
    ExposeKeyword,
    UserKeyword,
    WorkingDirectoryKeyword,
    VolumeKeyword,
    AsKeyword,
    StageNameKeyword,
    HealthCheckKeyword,
    OnBuildKeyword,

    //instructions
    FromInstruction,
    RunInstruction,
    EntryPointInstruction,
    CommandInstruction,
    CopyInstruction,
    HealthCheckInstruction,
    AddInstruction,
    EnvironmentVariableInstruction,
    BuildArgumentInstruction,
    ExposeInstruction,
    UserInstruction,
    WorkingDirectoryInstruction,


    StringToken,
    LineBreakToken,
    CommaToken,
    NumberToken,
    EndOfLineToken,
    BackSlashToken,
    MultiLineToken,
    AmpersandToken,
    PeriodToken,
    QuoteToken,
    UnderscoreToken,
    HyphenToken,
    ColonToken,
    SemicolonToken,
    CommentToken,
    ForwardSlash,
    ArgumentNameToken,
    AmpersandAmpersandToken,

    ImageStatement,
    LiteralExpression,
}